from collections import *
from itertools import *
from random import *
from time import *
from functools import *

'''
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''

def main():
    ans = set()
    for i in range(2,101):
        for j in range(2,101):
            ans.add(i**j)

    print(len(ans))


start = time()
main()
print('Program took %.02f seconds' % (time()-start))